"use client";
import {useEffect,useState} from "react";
import {ArrowRight,BookOpen,Check,FileText,LoaderCircle} from "lucide-react";
export default function CourseBuilder({onCreated}:{onCreated:(c:any)=>void}){
 const [states,setStates]=useState<any[]>([]),[state,setState]=useState("Arizona"),[grade,setGrade]=useState("10"),[area,setArea]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{fetch("/api/atlas").then(r=>r.json()).then(d=>setStates(d.states||[])).catch(()=>setError("Atlas could not be loaded."))},[]);
 const region=states.find(s=>s.state===state),areas=(region?.areas||[]).filter((a:any)=>!a.grades||a.grades.includes(grade)),selected=areas.find((a:any)=>a.area===area);
 async function generate(){if(!selected)return;setBusy(true);setError("");try{const r=await fetch("/api/generate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({state,grade,area})}),d=await r.json();if(!r.ok)throw Error(d.error);onCreated(d.course)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <section className="course-builder"><span className="eyebrow">ATLAS → PRESS</span><h3>Build a course companion</h3><p>Choose the source context. Press writes the lesson sequence, worked examples and tasks; Professor teaches from the saved companion.</p><div className="builder-fields"><label>State<select aria-label="Atlas state" value={state} disabled={busy} onChange={e=>{setState(e.target.value);setArea("")}}>{states.map(s=><option key={s.state}>{s.state}</option>)}</select></label><label>Grade<select aria-label="Atlas grade" value={grade} disabled={busy} onChange={e=>{setGrade(e.target.value);setArea("")}}>{["K",...Array.from({length:12},(_,i)=>String(i+1))].map(g=><option key={g}>{g}</option>)}</select></label><label>Subject<select aria-label="Atlas subject" value={area} disabled={busy} onChange={e=>setArea(e.target.value)}><option value="">Choose a subject</option>{areas.map((a:any)=><option key={a.area}>{a.area}</option>)}</select></label></div>{selected&&<div className="builder-source"><BookOpen size={16}/><div><b>{selected.excerptCitation||selected.statute}</b><p>{selected.sourceExcerpt}</p><small>Authority: {region.authority}. This statutory context is not a complete curriculum standard or approval.</small></div></div>}{error&&<p role="alert" className="builder-error">{error}</p>}<button className="primary" disabled={!selected||busy} onClick={generate}>{busy?<LoaderCircle size={15}/>:<FileText size={15}/>} {busy?"Press is writing your companion…":"Generate & save companion"}{!busy&&<ArrowRight size={15}/>}</button><small className="builder-boundary">AI-generated content requires instructional review before adoption. Generation may take a minute.</small></section>
}