export interface CatalogModule {
  code: string;
  title: string;
  trackCode: 'IPDG' | 'PDT' | 'ACA' | 'PPS' | 'CAT' | 'PPC' | 'BIZ' | 'PERS';
  trackTitle: string;
  term: number;
  level: '100' | '200' | '300' | '400';
  hours: number;
  category: 'Technical' | 'Business' | 'Personal' | 'Applied Capstone';
  safetyGate?: boolean;
  practicum?: boolean;
  description: string;
  slug: string;
}

export const ALL_CATALOG_MODULES: CatalogModule[] = [
  // ==========================================
  // IPDG - PROFESSIONAL DOG GROOMER (452 Tech + 12 Applied)
  // ==========================================
  {
    code: 'IPDG-101',
    title: 'Canine Breeds, Coat Types & Life Stages',
    trackCode: 'IPDG',
    trackTitle: 'Professional Dog Groomer',
    term: 1,
    level: '100',
    hours: 10,
    category: 'Technical',
    description: 'AKC breed classifications, coat categories, skin sensitivity, puppy and geriatric handling accommodations.',
    slug: 'professional-dog-groomer',
  },
  {
    code: 'IPDG-102',
    title: 'Bathing Chemistry, Equipment & Ergonomics',
    trackCode: 'IPDG',
    trackTitle: 'Professional Dog Groomer',
    term: 1,
    level: '100',
    hours: 12,
    category: 'Technical',
    description: 'Shampoo types, dilution ratios, eye/ear protection, tub ergonomics, water temperature, and high-velocity dryers.',
    slug: 'professional-dog-groomer',
  },
  {
    code: 'IPDG-103',
    title: 'Handling, Safety Gate & Table Restraints',
    trackCode: 'IPDG',
    trackTitle: 'Professional Dog Groomer',
    term: 1,
    level: '100',
    hours: 10,
    category: 'Technical',
    safetyGate: true,
    description: 'MANDATORY SAFETY GATE: Grooming loops, belly straps, bite mitigation, table posture, and safe lifting required before live-animal work.',
    slug: 'professional-dog-groomer',
  },
  {
    code: 'IPDG-201',
    title: 'Pre-Grooming Hygiene: Nails, Pads & Ears',
    trackCode: 'IPDG',
    trackTitle: 'Professional Dog Groomer',
    term: 2,
    level: '200',
    hours: 30,
    category: 'Technical',
    description: 'Nail clipping and electric grinding, pad clearing, ear cleaning, and sanitary area clipper preparation.',
    slug: 'professional-dog-groomer',
  },
  {
    code: 'IPDG-202',
    title: 'Introduction to Shears & Hand Scissoring',
    trackCode: 'IPDG',
    trackTitle: 'Professional Dog Groomer',
    term: 2,
    level: '200',
    hours: 20,
    category: 'Technical',
    description: 'Straight, curved, and thinning shear mechanics, proper finger tension, hand positioning, and line blending.',
    slug: 'professional-dog-groomer',
  },
  {
    code: 'IPDG-203',
    title: 'Clipper Mechanics, Blades & Snap-On Combs',
    trackCode: 'IPDG',
    trackTitle: 'Professional Dog Groomer',
    term: 2,
    level: '200',
    hours: 30,
    category: 'Technical',
    description: 'Blade numbering (#10, #7F, #5F, #4F), clipper maintenance, snap-on guard combs, and blade heat monitoring.',
    slug: 'professional-dog-groomer',
  },
  {
    code: 'IPDG-204',
    title: 'Drop Coats, Long Coats & Undercoat De-Shedding',
    trackCode: 'IPDG',
    trackTitle: 'Professional Dog Groomer',
    term: 2,
    level: '200',
    hours: 30,
    category: 'Technical',
    description: 'Carding, dematting rakes, line brushing, detangling spray conditioning, and coat moisture preservation.',
    slug: 'professional-dog-groomer',
  },
  {
    code: 'IPDG-205',
    title: 'Basic Breed Trims: Terriers & Sporting Group',
    trackCode: 'IPDG',
    trackTitle: 'Professional Dog Groomer',
    term: 2,
    level: '200',
    hours: 30,
    category: 'Technical',
    description: 'Jacket setting, skirt lines, furnishings preservation, and eyebrow/beard trimming for Schnauzers, Westies, and Spaniels.',
    slug: 'professional-dog-groomer',
  },
  {
    code: 'IPDG-301',
    title: 'Poodle Styling & Curly Coat Scissoring',
    trackCode: 'IPDG',
    trackTitle: 'Professional Dog Groomer',
    term: 3,
    level: '300',
    hours: 50,
    category: 'Technical',
    description: 'Lamb cuts, kennel trims, topknots, clean face and feet, tail pompons, and precision scissoring on curly coats.',
    slug: 'professional-dog-groomer',
  },
  {
    code: 'IPDG-302',
    title: 'Doodles, Mixed Breeds & Modern Pet Trims',
    trackCode: 'IPDG',
    trackTitle: 'Professional Dog Groomer',
    term: 3,
    level: '300',
    hours: 30,
    category: 'Technical',
    description: 'Teddy bear heads, donut muzzles, column legs, flared feet, and textured blends on doodle coats.',
    slug: 'professional-dog-groomer',
  },
  {
    code: 'IPDG-303',
    title: 'Double Coats, Nordic Breeds & Carding',
    trackCode: 'IPDG',
    trackTitle: 'Professional Dog Groomer',
    term: 3,
    level: '300',
    hours: 30,
    category: 'Technical',
    description: 'Preserving insulating layers, carding dense undercoat, silhouette tidy-ups, and heat-stroke risk prevention.',
    slug: 'professional-dog-groomer',
  },
  {
    code: 'IPDG-304',
    title: 'Hand Stripping Wire Breeds & Rolling Coats',
    trackCode: 'IPDG',
    trackTitle: 'Professional Dog Groomer',
    term: 3,
    level: '300',
    hours: 30,
    category: 'Technical',
    description: 'Stripping knives, chalking, finger pulling, maintaining wiry harsh texture, and humane scheduling for show/pet coats.',
    slug: 'professional-dog-groomer',
  },
  {
    code: 'IPDG-401',
    title: 'Senior, Disabled & Reactive Dog Accommodations',
    trackCode: 'IPDG',
    trackTitle: 'Professional Dog Groomer',
    term: 4,
    level: '400',
    hours: 50,
    category: 'Technical',
    description: 'Low-stress table work, timed rest breaks, orthopedic support, and compassionate senior pet handling.',
    slug: 'professional-dog-groomer',
  },
  {
    code: 'IPDG-402',
    title: 'Supervised Live-Client Salon Practicum & Speed Benchmarking',
    trackCode: 'IPDG',
    trackTitle: 'Professional Dog Groomer',
    term: 4,
    level: '400',
    hours: 50,
    category: 'Technical',
    practicum: true,
    description: 'Full commercial salon floor experience, time management, finish quality checks, and client handoffs under master groomer supervision.',
    slug: 'professional-dog-groomer',
  },
  {
    code: 'IPDG-403',
    title: 'Creative Grooming, Asian Fusion & Breed Standard Finishing',
    trackCode: 'IPDG',
    trackTitle: 'Professional Dog Groomer',
    term: 4,
    level: '400',
    hours: 40,
    category: 'Technical',
    description: 'Asian fusion expressions, flared legs, creative styling, and competition-level scissor finish.',
    slug: 'professional-dog-groomer',
  },
  {
    code: 'IPDG-BIZ',
    title: 'Professional Dog Grooming Salon Business Capstone',
    trackCode: 'IPDG',
    trackTitle: 'Professional Dog Groomer',
    term: 4,
    level: '400',
    hours: 12,
    category: 'Applied Capstone',
    description: 'Applied capstone defense: salon buildout budget, equipment selection, hourly pricing formula, intake waivers, and 90-day launch plan.',
    slug: 'professional-dog-groomer',
  },

  // ==========================================
  // PDT - PROFESSIONAL DOG TRAINER (236 Tech + 12 Applied)
  // ==========================================
  {
    code: 'PDT-101',
    title: 'Canine Ethology, Body Language & Stress Signals',
    trackCode: 'PDT',
    trackTitle: 'Professional Dog Trainer',
    term: 1,
    level: '100',
    hours: 10,
    category: 'Technical',
    description: 'Evolutionary history, developmental stages, subtle calming signals, stress escalation ladder, and ethological observation.',
    slug: 'professional-dog-trainer',
  },
  {
    code: 'PDT-102',
    title: 'Learning Theory: Operant & Classical Conditioning',
    trackCode: 'PDT',
    trackTitle: 'Professional Dog Trainer',
    term: 1,
    level: '100',
    hours: 12,
    category: 'Technical',
    description: 'Four quadrants of operant conditioning, marker training (clickers/verbal), reinforcement schedules, and extinction bursts.',
    slug: 'professional-dog-trainer',
  },
  {
    code: 'PDT-103',
    title: 'Equipment Mechanics, Leash Handling & Safety',
    trackCode: 'PDT',
    trackTitle: 'Professional Dog Trainer',
    term: 1,
    level: '100',
    hours: 10,
    category: 'Technical',
    description: 'Proper collar and harness fitting, leash grip techniques, slip lead safety, long lines, and spatial awareness.',
    slug: 'professional-dog-trainer',
  },
  {
    code: 'PDT-201',
    title: 'Basic Obedience: Luring, Shaping & Cue Capture',
    trackCode: 'PDT',
    trackTitle: 'Professional Dog Trainer',
    term: 2,
    level: '200',
    hours: 30,
    category: 'Technical',
    safetyGate: true,
    description: 'MANDATORY SAFETY GATE: Sit, down, stand, eye contact, hand targets, and fade food lures safely before live client coaching.',
    slug: 'professional-dog-trainer',
  },
  {
    code: 'PDT-202',
    title: 'Loose-Leash Walking & Recall Fundamentals',
    trackCode: 'PDT',
    trackTitle: 'Professional Dog Trainer',
    term: 2,
    level: '200',
    hours: 20,
    category: 'Technical',
    description: 'Directional changes, handler focus, long-line recalls, and managing environmental distractions.',
    slug: 'professional-dog-trainer',
  },
  {
    code: 'PDT-203',
    title: 'Impulse Control, Place Cue & Threshold Manners',
    trackCode: 'PDT',
    trackTitle: 'Professional Dog Trainer',
    term: 2,
    level: '200',
    hours: 30,
    category: 'Technical',
    description: 'Boundary training, crate manners, door thresholds, leave-it, and duration stays under distractions.',
    slug: 'professional-dog-trainer',
  },
  {
    code: 'PDT-301',
    title: 'Behavior Modification: Desensitization & Reactivity',
    trackCode: 'PDT',
    trackTitle: 'Professional Dog Trainer',
    term: 3,
    level: '300',
    hours: 30,
    category: 'Technical',
    description: 'Threshold management, counter-conditioning, resource guarding remediation, fear protocol, and trigger stacking prevention.',
    slug: 'professional-dog-trainer',
  },
  {
    code: 'PDT-302',
    title: 'Advanced Obedience, Proofing & Distraction Training',
    trackCode: 'PDT',
    trackTitle: 'Professional Dog Trainer',
    term: 3,
    level: '300',
    hours: 30,
    category: 'Technical',
    description: 'Distance commands, out-of-sight stays, emergency drop, whistle signals, and public access manners in commercial venues.',
    slug: 'professional-dog-trainer',
  },
  {
    code: 'PDT-401',
    title: 'Aggression Assessment, Bite Prevention & Safety Protocols',
    trackCode: 'PDT',
    trackTitle: 'Professional Dog Trainer',
    term: 4,
    level: '400',
    hours: 34,
    category: 'Technical',
    description: 'Evaluating bite histories, Dunbar bite scale, defensive leash handling, basket muzzling protocols, and fight interruption.',
    slug: 'professional-dog-trainer',
  },
  {
    code: 'PDT-402',
    title: 'Client Coaching, Private Lesson Delivery & Group Classes',
    trackCode: 'PDT',
    trackTitle: 'Professional Dog Trainer',
    term: 4,
    level: '400',
    hours: 30,
    category: 'Technical',
    practicum: true,
    description: 'Supervised 1-on-1 private lesson instruction with real owners, adult learning principles, and group class ring management.',
    slug: 'professional-dog-trainer',
  },
  {
    code: 'PDT-BIZ',
    title: 'Professional Dog Training Business Capstone',
    trackCode: 'PDT',
    trackTitle: 'Professional Dog Trainer',
    term: 4,
    level: '400',
    hours: 12,
    category: 'Applied Capstone',
    description: 'Applied capstone defense: complete training service menu, package pricing, client contract packet, and 90-day marketing launch plan.',
    slug: 'professional-dog-trainer',
  },

  // ==========================================
  // ACA - ANIMAL CARE ASSISTANT / DOG BATHER (112 Tech + 12 Applied)
  // ==========================================
  {
    code: 'ACA-101',
    title: 'Canine Handling, Body Language & Lift Mechanics',
    trackCode: 'ACA',
    trackTitle: 'Animal Care Assistant',
    term: 1,
    level: '100',
    hours: 10,
    category: 'Technical',
    description: 'Identifying dog breeds, life stages, fear postures, ergonomic two-person lifting for 40+ lb dogs, and kennel safety.',
    slug: 'animal-care-assistant',
  },
  {
    code: 'ACA-102',
    title: 'Bathing Chemistry, Coat Prep & Water Safety',
    trackCode: 'ACA',
    trackTitle: 'Animal Care Assistant',
    term: 1,
    level: '100',
    hours: 12,
    category: 'Technical',
    description: 'Shampoo types, dilution pumps, medicated dips, degreasers, water temperature regulation, and non-slip mats.',
    slug: 'animal-care-assistant',
  },
  {
    code: 'ACA-103',
    title: 'High-Velocity Drying & De-Shedding Techniques',
    trackCode: 'ACA',
    trackTitle: 'Animal Care Assistant',
    term: 1,
    level: '100',
    hours: 10,
    category: 'Technical',
    description: 'Velocity nozzle angles, happy hoodies, eye/ear protection, undercoat rakes, and de-shedding carding.',
    slug: 'animal-care-assistant',
  },
  {
    code: 'ACA-201',
    title: 'Salon Sanitation, Infection Control & Health Gate',
    trackCode: 'ACA',
    trackTitle: 'Animal Care Assistant',
    term: 2,
    level: '200',
    hours: 30,
    category: 'Technical',
    safetyGate: true,
    description: 'MANDATORY SAFETY GATE: Tub disinfection, kennel sanitation, identifying parasites (fleas, ticks, mites), and skin lesion reporting.',
    slug: 'animal-care-assistant',
  },
  {
    code: 'ACA-301',
    title: 'Pre-Grooming Hygiene, Nail Grinding & Ear Cleaning',
    trackCode: 'ACA',
    trackTitle: 'Animal Care Assistant',
    term: 3,
    level: '300',
    hours: 50,
    category: 'Technical',
    description: 'Pad trimming, sanitary area shaving, nail clipping & dremel grinding, ear cleaning, and bather speed benchmarking.',
    slug: 'animal-care-assistant',
  },
  {
    code: 'ACA-BIZ',
    title: 'Animal Care Assistant Applied Career & Business Capstone',
    trackCode: 'ACA',
    trackTitle: 'Animal Care Assistant',
    term: 4,
    level: '400',
    hours: 12,
    category: 'Applied Capstone',
    description: 'Portfolio of 30 documented dog baths, hygiene sign-offs, career ladder mapping (bather to salon owner), and interview prep.',
    slug: 'animal-care-assistant',
  },

  // ==========================================
  // PPS - PROFESSIONAL PET SITTER (14 Tech + 36 Biz + 6 Applied = 56 hr)
  // ==========================================
  {
    code: 'PPS-101',
    title: 'Pet Sitter Intake, Client Consultation & Home Security',
    trackCode: 'PPS',
    trackTitle: 'Professional Pet Sitter',
    term: 1,
    level: '100',
    hours: 3,
    category: 'Technical',
    description: 'Client intake meetings, key and lockbox security protocols, alarm systems, and emergency contact procedures.',
    slug: 'professional-pet-sitter',
  },
  {
    code: 'PPS-102',
    title: 'Multi-Species Care: Dogs, Cats, Birds & Small Animals',
    trackCode: 'PPS',
    trackTitle: 'Professional Pet Sitter',
    term: 1,
    level: '100',
    hours: 4,
    category: 'Technical',
    description: 'Species-specific routines, feeding schedules, cage cleaning, litter box monitoring, and behavioral stress signs.',
    slug: 'professional-pet-sitter',
  },
  {
    code: 'PPS-104',
    title: 'In-Home Handling & Leash Safety Gate',
    trackCode: 'PPS',
    trackTitle: 'Professional Pet Sitter',
    term: 1,
    level: '100',
    hours: 4,
    category: 'Technical',
    safetyGate: true,
    description: 'MANDATORY SAFETY GATE: Door bolting prevention, slip leads, harness verification, and outdoor dog encounter protocols.',
    slug: 'professional-pet-sitter',
  },
  {
    code: 'PPS-105',
    title: 'Pet First Aid, Medication Admin & Medical Emergencies',
    trackCode: 'PPS',
    trackTitle: 'Professional Pet Sitter',
    term: 1,
    level: '100',
    hours: 3,
    category: 'Technical',
    safetyGate: true,
    description: 'MANDATORY SAFETY GATE: Administering oral/topical medications, insulin injections basics, CPR, choking response, and vet transport.',
    slug: 'professional-pet-sitter',
  },
  {
    code: 'PPS-BIZ',
    title: 'Pet Sitter Applied Business Launch Capstone',
    trackCode: 'PPS',
    trackTitle: 'Professional Pet Sitter',
    term: 4,
    level: '400',
    hours: 6,
    category: 'Applied Capstone',
    description: 'Complete launch plan: service radius, route optimization, pricing menu, client service agreement, and liability insurance checklist.',
    slug: 'professional-pet-sitter',
  },

  // ==========================================
  // CAT - PROFESSIONAL CAT GROOMER (16 Tech + 36 Biz + 6 Applied = 58 hr)
  // ==========================================
  {
    code: 'CAT-101',
    title: 'Feline Breeds, Anatomy & Coat Types',
    trackCode: 'CAT',
    trackTitle: 'Professional Cat Groomer',
    term: 1,
    level: '100',
    hours: 4,
    category: 'Technical',
    description: 'Recognizing cat breeds, skeletal differences from dogs, thin skin anatomy, and shorthair vs longhair coat textures.',
    slug: 'professional-cat-groomer',
  },
  {
    code: 'CAT-102',
    title: 'Low-Stress Feline Handling & Towel Wraps Safety Gate',
    trackCode: 'CAT',
    trackTitle: 'Professional Cat Groomer',
    term: 1,
    level: '100',
    hours: 4,
    category: 'Technical',
    safetyGate: true,
    description: 'MANDATORY SAFETY GATE: Reading feline body language (ears, whiskers, tail), burrito towel wraps, scruffing alternatives, and bite avoidance.',
    slug: 'professional-cat-groomer',
  },
  {
    code: 'CAT-103',
    title: 'Cat Bathing, Degreasing & Stress-Free Drying',
    trackCode: 'CAT',
    trackTitle: 'Professional Cat Groomer',
    term: 1,
    level: '100',
    hours: 4,
    category: 'Technical',
    description: 'Stud tail degreasing, safe face washing, water acclimation, low-noise drying cages, and ambient temperature regulation.',
    slug: 'professional-cat-groomer',
  },
  {
    code: 'CAT-104',
    title: 'Lion Cuts, Comb Cuts, Sanitary Trims & Dematting',
    trackCode: 'CAT',
    trackTitle: 'Professional Cat Groomer',
    term: 1,
    level: '100',
    hours: 4,
    category: 'Technical',
    description: '#10 blade safety over feline skin folds, lion cut styling, sanitary trimming, toe tufts, and humane pelt removal.',
    slug: 'professional-cat-groomer',
  },
  {
    code: 'CAT-BIZ',
    title: 'Professional Cat Grooming Business Capstone',
    trackCode: 'CAT',
    trackTitle: 'Professional Cat Groomer',
    term: 4,
    level: '400',
    hours: 6,
    category: 'Applied Capstone',
    description: 'Feline specialty salon pricing, quiet cat-only hours scheduling, client waivers, scratch protocols, and marketing plan.',
    slug: 'professional-cat-groomer',
  },

  // ==========================================
  // PPC - PROFESSIONAL PET CARE & BUSINESS OWNERSHIP (27 Tech + 36 Applied = 636 hr)
  // ==========================================
  {
    code: 'PPC-101',
    title: 'Animal Handling & Restraint Mechanics',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 1,
    level: '100',
    hours: 20,
    category: 'Technical',
    description: 'Safe physical mechanics and reading canine and feline stress signals across salon, kennel, and transit environments.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-102',
    title: 'Pet Health, CPR & First Aid Protocol',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 1,
    level: '100',
    hours: 20,
    category: 'Technical',
    description: 'Vital signs assessment, canine and feline CPR, choking management, heat stroke protocol, and first responder triage.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-103',
    title: 'Breed Recognition & Temperament Assessment',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 1,
    level: '100',
    hours: 20,
    category: 'Technical',
    description: 'AKC breed group behavioral archetypes, cat breed traits, social compatibility testing, and playgroup evaluation.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-104',
    title: 'Bathing & Salon Preparation Fundamentals',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 1,
    level: '100',
    hours: 20,
    category: 'Technical',
    description: 'Bathing chemistry, high-velocity blowouts, de-shedding rakes, pad trimming, and hygiene prep routines.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-105',
    title: 'Salon Sanitation & Infection Control Safety Gate',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 1,
    level: '100',
    hours: 20,
    category: 'Technical',
    safetyGate: true,
    description: 'MANDATORY SAFETY GATE: Pathogen containment (Parvo, Kennel Cough, Ringworm), chemical safety (OSHA SDS), and kennel sanitation.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-106',
    title: 'Customer Intake & Service Consultation',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 1,
    level: '100',
    hours: 15,
    category: 'Technical',
    description: 'Client consultation dialogues, health checklists, service agreement signatures, and expectation management.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-201',
    title: 'Intermediate Canine Grooming & Scissor Control Safety Gate',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 2,
    level: '200',
    hours: 35,
    category: 'Technical',
    safetyGate: true,
    description: 'MANDATORY SAFETY GATE: Blade safety (#10, #7F, #5F, #4F), guard comb clipping, shear balance, and sanitary trims.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-202',
    title: 'Basic Obedience & Canine Learning Theory',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 2,
    level: '200',
    hours: 35,
    category: 'Technical',
    description: 'Operant conditioning, marker mechanics, luring sit/down/stay, loose-leash walking, and crate acclimation.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-203',
    title: 'Multi-Species Care & In-Home Pet Sitting',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 2,
    level: '200',
    hours: 35,
    category: 'Technical',
    description: 'In-home visit management, feline routines, pocket pets, key security protocols, and client daily photo logs.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-204',
    title: 'Cat Handling & Feline Grooming Fundamentals',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 2,
    level: '200',
    hours: 35,
    category: 'Technical',
    description: 'Low-stress feline handling, towel wraps, lion cuts, sanitary trims, and preventing handling escalation.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-205',
    title: 'Behavior Problem Identification & Solutions',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 2,
    level: '200',
    hours: 30,
    category: 'Technical',
    description: 'Jumping, excessive barking, separation distress, minor resource guarding, and counter-conditioning techniques.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-301',
    title: 'Advanced Breed Pattern Styling & Hand Scissoring',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 3,
    level: '300',
    hours: 40,
    category: 'Technical',
    description: 'Poodle lamb cuts, Teddy Bear head trims, Terrier wire coats, curved shear beveling, and finishing symmetry.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-302',
    title: 'Behavior Modification & Reactivity Management',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 3,
    level: '300',
    hours: 40,
    category: 'Technical',
    description: 'Leash reactivity, barrier frustration, fear-based aggression triggers, and threshold desensitization.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-303',
    title: 'Commercial Daycare & Boarding Facility Operations',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 3,
    level: '300',
    hours: 40,
    category: 'Technical',
    description: 'Large group play dynamics, red-flag behaviors, air-exchange systems, kennel rotations, and overnight supervision.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-304',
    title: 'Mobile Pet Care Operations & Van Outfitting',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 3,
    level: '300',
    hours: 35,
    category: 'Technical',
    description: 'Inverter/generator power systems, water tank management, winterization, mobile route optimization, and vehicle maintenance.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-305',
    title: 'Multi-Service Facility Logistics & Scheduling',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 3,
    level: '300',
    hours: 40,
    category: 'Technical',
    description: 'Synchronizing grooming bays, training rings, and daycare packs without operational bottlenecks.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-306',
    title: 'High-Risk Handling & Aggression Protocols Safety Gate',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 3,
    level: '300',
    hours: 30,
    category: 'Technical',
    safetyGate: true,
    description: 'MANDATORY SAFETY GATE: Defensive leash work, basket muzzles, bite stick protocols, and high-risk client intake boundaries.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-401',
    title: 'Advanced Feline Styling & Specialty Services',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 4,
    level: '400',
    hours: 10,
    category: 'Technical',
    description: 'Precision feline comb cuts, coat de-matting under sedation partnerships, and senior cat comfort styling.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-402',
    title: 'Service Dog Basics & Public Access Foundations',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 4,
    level: '400',
    hours: 10,
    category: 'Technical',
    description: 'ADA guidelines, service dog vs ESA vs therapy dog definitions, and public access manners training.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-403',
    title: 'Emergency First Responder & Triage Safety Gate',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 4,
    level: '400',
    hours: 10,
    category: 'Technical',
    safetyGate: true,
    description: 'MANDATORY SAFETY GATE: Gastric torsion (bloat) triage, vehicle accident stabilization, and transport packaging.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-404',
    title: 'Master Grooming Speed & Quality Benchmarking',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 4,
    level: '400',
    hours: 10,
    category: 'Technical',
    description: 'Achieving industry standard timing (60-75 min per full groom) while maintaining superior hand scissoring finish.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-405',
    title: 'Complex Behavior Case Management Safety Gate',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 4,
    level: '400',
    hours: 10,
    category: 'Technical',
    safetyGate: true,
    description: 'MANDATORY SAFETY GATE: Severe separation anxiety case plans, veterinary behavioral partnerships, and psychotropic medication awareness.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-406',
    title: 'Pet Care Business Acquisition & Franchising',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 4,
    level: '400',
    hours: 10,
    category: 'Technical',
    description: 'Due diligence on existing salon acquisitions, franchise disclosure evaluation, and multi-location expansion.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-407',
    title: 'Staff Training & Salon Leadership Development',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 4,
    level: '400',
    hours: 10,
    category: 'Technical',
    description: 'Standard operating procedure (SOP) design, hiring bathers/groomers, apprenticeship mentorship, and safety drills.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-408',
    title: 'Private Training Class Delivery Practicum',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 4,
    level: '400',
    hours: 10,
    category: 'Technical',
    practicum: true,
    description: 'Delivering live private client training consultations with full behavioral evaluation reports.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-409',
    title: 'Multi-Service Practicum Supervised Client Log',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 4,
    level: '400',
    hours: 10,
    category: 'Technical',
    practicum: true,
    description: 'Verified multi-service log across salon floor, training floor, and in-home client visits.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-410',
    title: 'Terminal Safety & Master Operator Board Safety Gate',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 4,
    level: '400',
    hours: 10,
    category: 'Technical',
    safetyGate: true,
    description: 'FINAL SAFETY GATE: Comprehensive practical exam evaluating handling, blade safety, biosecurity, and legal risk governance.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PPC-BIZ',
    title: 'Applied Multi-Service Business Capstone Defense',
    trackCode: 'PPC',
    trackTitle: 'Professional Pet Care & Business Ownership',
    term: 4,
    level: '400',
    hours: 36,
    category: 'Applied Capstone',
    description: 'Comprehensive business plan defense before owner panel: financial models, 3-year cash flow projections, staffing hierarchy, and marketing launch.',
    slug: 'pet-care-business-ownership',
  },

  // ==========================================
  // BUSINESS & PERSONAL MASTERY SPINE (144 Modules · 864 Hours)
  // Shared across IPDG, PDT, ACA, PPC (and key modules in PPS, CAT)
  // ==========================================
  {
    code: 'BUS-101',
    title: 'Pet Industry Business Fundamentals & Structure',
    trackCode: 'BIZ',
    trackTitle: 'Business & Leadership',
    term: 1,
    level: '100',
    hours: 6,
    category: 'Business',
    description: 'Entity selection (LLC, S-Corp), market analysis, competitive positioning, and business mission.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'BUS-203',
    title: 'Client Retention, Key Security & Scheduling Logistics',
    trackCode: 'BIZ',
    trackTitle: 'Business & Leadership',
    term: 2,
    level: '200',
    hours: 6,
    category: 'Business',
    description: 'Managing appointment calendars, lockbox security, recurring booking subscriptions, and retention loops.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'MKT-304',
    title: 'Local Service Marketing & Referral Partnerships',
    trackCode: 'BIZ',
    trackTitle: 'Marketing, Branding & SEO',
    term: 3,
    level: '300',
    hours: 6,
    category: 'Business',
    description: 'Veterinary referral networks, pet food boutique partnerships, Google Business Profile optimization, and local community outreach.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'FIN-101',
    title: 'Sole Proprietorship, Bookkeeping & Cash Flow',
    trackCode: 'BIZ',
    trackTitle: 'Financial Mastery & Bookkeeping',
    term: 1,
    level: '100',
    hours: 6,
    category: 'Business',
    description: 'Setting up chart of accounts, tracking deductible business expenses, sales tax collection, and cash flow budgeting.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'LEG-101',
    title: 'Licensing, Zoning & Insurance for Pet Care Providers',
    trackCode: 'BIZ',
    trackTitle: 'Legal & Regulatory Governance',
    term: 1,
    level: '100',
    hours: 6,
    category: 'Business',
    description: 'Municipal animal permits, commercial general liability, animal bailee floater policies, and bonding.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'LEG-103',
    title: 'Service Contracts, Bailment & Client Liability Waivers',
    trackCode: 'BIZ',
    trackTitle: 'Legal & Regulatory Governance',
    term: 1,
    level: '100',
    hours: 6,
    category: 'Business',
    description: 'Enforceable pet care agreements, emergency medical authorization clauses, matting release forms, and veterinary consent.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'TEC-101',
    title: 'Owner-Operator Digital Toolkit & CRM Setup',
    trackCode: 'BIZ',
    trackTitle: 'Technology & AI Systems',
    term: 1,
    level: '100',
    hours: 6,
    category: 'Business',
    description: 'Configuring cloud booking engines, automated client text reminders, digital client cards, and contactless payments.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'LSH-101',
    title: 'Personal Readiness, Time Management & Professional Discipline',
    trackCode: 'PERS',
    trackTitle: 'Life Skills & Personal Readiness',
    term: 1,
    level: '100',
    hours: 6,
    category: 'Personal',
    description: 'Daily operational routines, sleep hygiene, punctual attendance habits, and professional communication standards.',
    slug: 'pet-care-business-ownership',
  },
  {
    code: 'PER-101',
    title: 'Personal Mastery, Mindset & Emotional Resilience',
    trackCode: 'PERS',
    trackTitle: 'Personal Mastery & Lifelong Growth',
    term: 1,
    level: '100',
    hours: 6,
    category: 'Personal',
    description: 'Managing occupational stress, compassion fatigue prevention, constructive feedback reception, and long-term goal setting.',
    slug: 'pet-care-business-ownership',
  },
];

// Search Helper
export function searchCatalog(query: string): CatalogModule[] {
  if (!query || !query.trim()) return ALL_CATALOG_MODULES;
  const q = query.toLowerCase().trim();

  return ALL_CATALOG_MODULES.filter((m) => {
    return (
      m.code.toLowerCase().includes(q) ||
      m.title.toLowerCase().includes(q) ||
      m.description.toLowerCase().includes(q) ||
      m.trackCode.toLowerCase().includes(q) ||
      m.trackTitle.toLowerCase().includes(q) ||
      m.category.toLowerCase().includes(q) ||
      (q.includes('safety') && m.safetyGate) ||
      (q.includes('gate') && m.safetyGate) ||
      (q.includes('practicum') && m.practicum)
    );
  });
}
